export const NATIVE_LANGUAGE_OPTIONS = [
    { value: "", label: "Select native language" },
    { value: "English", label: "English" },
    { value: "Spanish", label: "Spanish" },
    { value: "French", label: "French" },
    { value: "German", label: "German" },
    { value: "Italian", label: "Italian" },
    { value: "Portuguese", label: "Portuguese" },
    { value: "Arabic", label: "Arabic" },
    { value: "Hindi", label: "Hindi" },
    { value: "Bengali", label: "Bengali" },
    { value: "Urdu", label: "Urdu" },
    { value: "Mandarin", label: "Mandarin" },
    { value: "Cantonese", label: "Cantonese" },
    { value: "Japanese", label: "Japanese" },
    { value: "Korean", label: "Korean" },
    { value: "Vietnamese", label: "Vietnamese" },
    { value: "Russian", label: "Russian" },
    { value: "Turkish", label: "Turkish" },
    { value: "Other", label: "Other" },
];