-- Sample data for properties table
-- Run this in your Supabase SQL editor to populate the database with sample properties

INSERT INTO public.properties (
  title,
  description,
  address,
  location,
  latitude,
  longitude,
  property_type,
  bedrooms,
  bathrooms,
  car_spaces,
  furnished,
  amenities,
  images,
  is_published
) VALUES
(
  'Modern Studio Apartment in CBD',
  'Beautiful modern studio apartment located in the heart of the CBD. Walking distance to universities and public transport.',
  '{"street": "123 Elizabeth Street", "suburb": "Melbourne", "state": "VIC", "postcode": "3000"}'::jsonb,
  '{"city": "Melbourne", "state": "VIC", "country": "Australia"}'::jsonb,
  -37.8136,
  144.9631,
  'Apartment',
  1,
  1,
  0,
  true,
  ARRAY['WiFi', 'Air Conditioning', 'Kitchen', 'Washer/Dryer'],
  ARRAY['/window.svg'],
  true
),
(
  'Spacious 2BR Unit Near University',
  'Bright and spacious 2-bedroom unit, perfect for students. Close to public transport and shopping centers.',
  '{"street": "45 Lygon Street", "suburb": "Carlton", "state": "VIC", "postcode": "3053"}'::jsonb,
  '{"city": "Melbourne", "state": "VIC", "country": "Australia"}'::jsonb,
  -37.8005,
  144.9673,
  'Unit',
  2,
  1,
  1,
  false,
  ARRAY['WiFi', 'Heating', 'Balcony', 'Study Room'],
  ARRAY['/window.svg'],
  true
),
(
  'Cozy Share House Room',
  'Single room in a friendly 4-bedroom share house. Great location near campus and amenities.',
  '{"street": "78 Grattan Street", "suburb": "Parkville", "state": "VIC", "postcode": "3052"}'::jsonb,
  '{"city": "Melbourne", "state": "VIC", "country": "Australia"}'::jsonb,
  -37.7833,
  144.9576,
  'House',
  1,
  1,
  0,
  true,
  ARRAY['WiFi', 'Shared Kitchen', 'Garden', 'Parking'],
  ARRAY['/window.svg'],
  true
),
(
  'Luxury 3BR Townhouse',
  'Stunning 3-bedroom townhouse with modern finishes. Perfect for small families or groups.',
  '{"street": "22 Brunswick Street", "suburb": "Fitzroy", "state": "VIC", "postcode": "3065"}'::jsonb,
  '{"city": "Melbourne", "state": "VIC", "country": "Australia"}'::jsonb,
  -37.7987,
  144.9789,
  'Townhouse',
  3,
  2,
  2,
  true,
  ARRAY['WiFi', 'Air Conditioning', 'Dishwasher', 'Garage', 'BBQ Area'],
  ARRAY['/window.svg'],
  true
),
(
  'Budget-Friendly Student Room',
  'Affordable single room perfect for students on a budget. All utilities included.',
  '{"street": "156 Sydney Road", "suburb": "Brunswick", "state": "VIC", "postcode": "3056"}'::jsonb,
  '{"city": "Melbourne", "state": "VIC", "country": "Australia"}'::jsonb,
  -37.7667,
  144.9567,
  'House',
  1,
  1,
  0,
  false,
  ARRAY['WiFi', 'Shared Kitchen', 'Laundry'],
  ARRAY['/window.svg'],
  true
),
(
  'Executive 2BR Apartment with Views',
  'Luxury apartment with stunning city views. Fully furnished with high-end appliances.',
  '{"street": "88 Southbank Boulevard", "suburb": "Southbank", "state": "VIC", "postcode": "3006"}'::jsonb,
  '{"city": "Melbourne", "state": "VIC", "country": "Australia"}'::jsonb,
  -37.8259,
  144.9632,
  'Apartment',
  2,
  2,
  1,
  true,
  ARRAY['WiFi', 'Gym', 'Pool', 'Concierge', 'Air Conditioning'],
  ARRAY['/window.svg'],
  true
);
